version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  mongodb_data:
