version: '3'
services:
  app:
      build:
        dockerfile: Dockerfile
        context: .
        target: final
      container_name: app
      ports:
        - 8080:8080
      restart: unless-stopped
      depends_on:
        - mongodb
      networks:
        - auth-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongoui
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - auth-network

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth-network

  redis:
    image: redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass root
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - auth-network

volumes:
  mongodb_data:

networks:
  auth-network:
    driver: bridge